### ISSUE TITLE
Library crashes build time on iOS

### ISSUE THREAD

**Issue by Schadenfeude** [hfhbd/kotlinx-uuid#150]
`Could not find "/Users/schadenfreude/.gradle/caches/modules-2/files-2.1/app.softwork/kotlinx-uuid-core-iosx64/0.0.16/8ec27f37d3e7e7ecae239da2390b131b3b09417/kotlinx-uuid-core.klib" in [/Users/schadenfreude/StudioProjects/project/mobile, /Users/schadenfreude/.konan/klib, /Users/schadenfreude/.konan/kotlin-native-prebuilt-macos-aarch64-1.6.21/klib/common, /Users/schadenfreude/.konan/kotlin-native-prebuilt-macos-aarch64-1.6.21/klib/platform/ios_x64]`

I'm getting this when I try to compile my iOS project with version 0.0.16 and 0.0.17 (tested only these 2). The Android project runs without problem.

**Comment by hfhbd** [comment]
Hey, I didn't see this issue. What Kotlin version do you use?

**Comment by Schadenfeude** [comment]
Kotlin plugin and stlib version used was `1.7.10`

**Comment by hfhbd** [comment]
`0.0.16` and `0.0.17` are identical, `0.0.17` only adds watchOS and tvOS support. Both versions use Kotlin `1.7.10` too.
Could you create a reproducer or more logs? Because I can't reproduce it with this sample: 
[untitled.zip](https://github.com/hfhbd/kotlinx-uuid/files/9673126/untitled.zip)

**Comment by Schadenfeude** [comment]
Sorry, I don't have a committed version of this to git. We decided not to use the library and I just wrote a simple `expect/actual` function that provides us with a random NSUUID or a Java UUID in the respective platforms.

**Comment by hfhbd** [comment]
Okay.
Yeah using `expect/actual` is a good alternative too.
