### ISSUE TITLE
WASM JS support

### ISSUE THREAD

**Issue by hfhbd** [hfhbd/kotlinx-uuid#286]

**Comment by Melodeiro** [comment]
Any update on this? Looks like there is more and more UI and core libraries implemented wasmjs support lately, so having the uuid library for fullstack experience will be a good addition

**Comment by hfhbd** [comment]
Kotlin 2.0.20-Beta2 will introduce native Uuid class with WASM (JS and WASI) support too, so I won't add WASM support by myself. This library will be reduced for wrappers, interop and uuidv7 support.
