### ISSUE TITLE
kotlinx?

### ISSUE THREAD

**Issue by jessiejs** [hfhbd/kotlinx-uuid#320]
This isn't an official Kotlinx library? Why is it under the kotlinx library? It should be under something like `me.hfhbd.uuid`.

**Comment by hfhbd** [comment]
> Why is it under the kotlinx library?

As you can read in the README this library is a fork that was released under `kotlinx.uuid` because it was the idea to publish the upstream library as an official Kotlinx library.
But this never happened. 

I will update the package name thought: see #199
