### ISSUE TITLE
Heads-up: Kotlin 2.0.20 Standard Lib now comes with native UUID support

### ISSUE THREAD

**Issue by janseeger** [hfhbd/kotlinx-uuid#392]
https://kotlinlang.org/docs/whatsnew2020.html#support-for-uuids-in-the-common-kotlin-standard-library

**Comment by hfhbd** [comment]
What's the reason for this issue? 0.1.0+ requires 2.0.20 and already uses kotlin.uuid.Uuid, https://github.com/hfhbd/kotlinx-uuid/releases/tag/v0.1.0

**Comment by hfhbd** [comment]
There is no alias and no migration, I completely removed the custom implementation and only added helper methods for kotlin.uuid.Uuid.
